language: cpp
os:
    - linux
    - osx
dist: trusty
sudo: required
osx_image: xcode8.3

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CI=./ci/sierra; else export CI=./ci/trusty; fi
    - $CI before_install
install:
    - $CI install
script:
    - $CI script
