version: '{build}'
skip_tags: true
shallow_clone: true

environment:
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

install:
- SET PATH=%ProgramFiles(x86)%\WiX Toolset v3.11\bin;%PATH%
- C:\Qt\5.11\msvc2017_64\bin\qtenv2.bat
- '"%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"'

build_script:
- cd %APPVEYOR_BUILD_FOLDER%\ci\windows
- Build
- MakeInstaller

artifacts:
- path: ci/windows/BullyCPP.exe
  name: BullyCPP.exe
- path: ci/windows/BullyCPPw.exe
  name: BullyCPPw.exe
- path: ci/windows/BullyCPP.msi
  name: BullyCPP.msi
